<?php

return [
    'HELLO' => 'Hello',
    'Ignore' => 'If you have not made this request, simply ignore this letter',
    'ConfirmCode' => 'Confirmation code',
    'WasSent' => 'This email was sent to',
    'Autogenerated' => 'This letter was generated automatically. Please do not reply to this message.',
    'goTo' => 'Go to publication',
    'GoToChat' => 'Go To Chat',
    'PublicationSuccessTitle' => 'Publication Succsesfuly!',
    'PublicationCancelledTitle' => 'Publication Canceled!',
    'PublicationSuccessText' => 'Your publication (or post, or profile) is active! You can change your publication (or post, or profile) in your personal account.',
    'PublicationCancelledText' => 'Your publication (or post or profile) has been cancelled! Go to your personal account for detailed information. (or more information)',
    'PublicationNewMessageTitle' => 'New message',
    'PublicationNewMessageText' => 'The user sent you a new message regarding the advertisement',
    'SupportNewMessageTitle' => 'New Support message',
    'SupportNewMessageText' => 'You have received a message from (technical support, help desk, custom service, support service, or the support service) regarding your request',
    'PublicationPaymentSuccessTitle' => 'The payment suscsesfuly!',
    'PublicationPaymentSuccessText' => 'Payment was successful! You can track the status of your publication (or post, or profile) in your personal account.',
];
