<div class="footer" style="background-color: #f7f9fc; padding: 32px;">
    <style>
        .footer {
            background-color: #f7f9fc;
        }

        .footer .description {
            line-height: 20px;
            color: var(--color-darkslategray);
            padding-bottom: 44px;
        }

        .footer .description .mailto {
            text-decoration: underline;
            color: #6875de;
        }

        .footer .logo {
            padding-bottom: 32px;
        }

        .footer .links {
            padding-bottom: 24px;
        }

        .footer .links a {
            line-height: 100%;
            font-weight: 500;
            font-family: Helvetica;
            text-decoration: none;
            color: #6a7c94;
            padding-right: 32px;
        }

        .footer .links a:hover {
            color: #6875de !important;
        }

        .copyright-info {
            font-size: 12px;
            line-height: 14px;
        }
    </style>
    <div class="description" style="line-height: 20px; color: var(--color-darkslategray); padding-bottom: 44px;">
        <span>{{__('mails.WasSent', [], $local ?? null)}}</span>
        <a class="mailto" style="text-decoration: underline; color: #6875de;" href="{{$user->email}}">{{$user->email}}.</a>
        <span>
            {{__('mails.Autogenerated', [], $local ?? null)}}
        </span>
    </div>
    <a href="https://looknet.com">
        <img
            class="logo"
            style="padding-bottom: 32px; object-fit: contain; width: 102px; height: 21px;"
            src="{{asset('img/mails/logo-footer.png')}}"
        />
    </a>
    <div class="links" style="padding-bottom: 24px;">
        <a style="line-height: 100%; font-weight: 500; font-family: Helvetica; text-decoration: none; color: #6a7c94; padding-right: 32px;" href="https://looknet.com">Website</a>
        <a style="line-height: 100%; font-weight: 500; font-family: Helvetica; text-decoration: none; color: #6a7c94; padding-right: 32px;" href="https://looknet.com/privacy-police">Privacy police</a>
        <a style="line-height: 100%; font-weight: 500; font-family: Helvetica; text-decoration: none; color: #6a7c94; padding-right: 32px;" href="https://looknet.com/support">Support</a>
        <a style="line-height: 100%; font-weight: 500; font-family: Helvetica; text-decoration: none; color: #6a7c94; padding-right: 32px;" href="https://looknet.com/contacts">Contacts</a>
    </div>
    <div class="copyright-info" style="font-size: 12px; line-height: 14px;">
        Copyright © {{date('Y')}} {{ config('app.name') }} Inc. Free advertising web site.
    </div>
</div>
